### ISSUE TITLE
Maybe newbie error but not getting IP

### ISSUE THREAD

**Issue by zwollerob** [scyto/docker-UnifiBrowser#2]
Hello,

I have installed the docker registry on my Synlogy NAS.
I use an MACVLAN network. So every docker gets his own IP.
But when starting I see : 

Listening on http://0:8000 | stdout
-- | --

Tried it also with Bridge and elevated rights.. But no succes..

Any tips?

**Comment by scyto** [comment]
yup that's normal, just means 'all interfaces' i think, i see the same in my logs, my container is attached to bridge, in the synology docker container log tab you should see more than that - the next line should confirm the document root, you filled out all the env vars right?

Not sure why you would need to macvlan this, but your call, for testing i suggest using the synology UI (and thus bridge or host networking) not the command line and making sure you filled out EVERY env var (the UI will show it prepopulated and make it clear where you need to change)

By the way if you use macvlan and you edit the config in the UI you may find you break the macvaln (epecially if you use the clear action).  Once you use macvlan you are commited to doing all operations via the command line to be sure  Personally i only macvlan special containers - such as pihole (because of ipv6) and anything needing broadcast protocols to work.  For everything else bridge or host should suffice....

**Comment by scyto** [comment]
@zwollerob did you get it working?

**Comment by scyto** [comment]
closing, no response, reopen if you didn't get it working.
